import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";
import "../scss/main.scss";
import PageRender from "./PageRender";
import { Providers } from "@/redux/provider";
import Navbar from "@/components/partials/Header";
import Footers from "@/components/partials/Footer";

export const metadata: Metadata = {
  title: "ShareTrip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning={true}>
        <Providers>
          <PageRender>
            <Navbar/>
              {children}
            <Footers/>
          </PageRender>
        </Providers>
      </body>
    </html>
  );
}